base_url = "https://uofg.webr.ing"

# ring information
ring_name = "University of Glasgow"
ring_description = "🎓 webring for students/alumni of UofG!"
ring_owner = "newt"
ring_owner_site = "https://newty.dev"

# paths
path_assets = "assets"
path_templates = "templates"